version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: scripts/download_code.sh
    - location: scripts/unzip_code.sh
      runas: root
 
  ApplicationStart:
    - location: scripts/portal-start.sh
      timeout: 180
      runas: root
