version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: scripts/DownloadSourceCode_tar.sh
      timeout: 180
      runas: root
 
  ApplicationStart:
    - location: scripts/portal-start.sh
      timeout: 180
      runas: root
